name: Build and deploy Python app to Azure Web App - a2-ux-test
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1C5B5173E31744F993902CC412719140 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DD9F8706470A483698E0DF4C8ACECB91 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6CBC59877995486587B77EFE808FC63B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'a2-ux-test'
          slot-name: 'Production'
